import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:zip_recipes_app/firebase/services/ingredient.dart';
import 'package:zip_recipes_app/firebase/services/ingredients_service.dart';
import 'package:zip_recipes_app/firebase/services/recipe.dart';
import 'package:zip_recipes_app/firebase/services/recipe_service.dart';
import 'auth/login.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(); // Initialize Firebase

  //addSampleData();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: LoginPage(),
    );
  }
}




void addSampleData() async {
  final ingredientService = IngredientService();
  final recipeService = RecipeService();

  // Add some ingredients
  final riceId = await ingredientService.addIngredient(Ingredient(id: '', name: 'Rice', type: 'Grain'));
  final appleId = await ingredientService.addIngredient(Ingredient(id: '', name: 'Apple', type: 'Fruit'));
  final lettuceId = await ingredientService.addIngredient(Ingredient(id: '', name: 'Lettuce', type: 'Vegetable'));
  final chickenId = await ingredientService.addIngredient(Ingredient(id: '', name: 'Chicken', type: 'Meat'));
  final tomatoId = await ingredientService.addIngredient(Ingredient(id: '', name: 'Tomato', type: 'Vegetable'));
  final cheeseId = await ingredientService.addIngredient(Ingredient(id: '', name: 'Cheese', type: 'Dairy'));

  if (riceId != null &&
      appleId != null &&
      lettuceId != null &&
      chickenId != null &&
      tomatoId != null &&
      cheeseId != null) {
    // Add the first recipe: Tuna Salad
    final tunaSaladId = await recipeService.addRecipe(Recipe(
      id: '', // ID will be generated by Firebase
      name: 'Tuna Salad',
      image: 'assets/images/icons/food.png',
      salt: '2g',
      fat: '10g',
      energy: '250kcal',
      protein: '15g',
      ingredients: [
        Ingredient(id: riceId, name: 'Rice', type: 'Grain'),
        Ingredient(id: appleId, name: 'Apple', type: 'Fruit'),
        Ingredient(id: lettuceId, name: 'Lettuce', type: 'Vegetable'),
      ],
      information: 'This is a simple and healthy tuna salad recipe.',
      guide: [
        RecipeStep(description: 'Preheat the oven to 350°F (175°C).'),
        RecipeStep(description: 'Mix dry ingredients together.', timer: 30),
        RecipeStep(description: 'Add wet ingredients and mix until smooth.', timer: 30),
        RecipeStep(description: 'Bake for 30 minutes.', timer: 30),
        RecipeStep(description: 'Let it cool for 15 minutes.', timer: 15),
      ],
    ));
    print('Tuna Salad Recipe added with ID: $tunaSaladId');

    // Add the second recipe: Grilled Chicken Salad
    final grilledChickenSaladId = await recipeService.addRecipe(Recipe(
      id: '', // ID will be generated by Firebase
      name: 'Grilled Chicken Salad',
      image: 'assets/images/icons/grilled_chicken.png',
      salt: '3g',
      fat: '12g',
      energy: '300kcal',
      protein: '25g',
      ingredients: [
        Ingredient(id: chickenId, name: 'Chicken', type: 'Meat'),
        Ingredient(id: lettuceId, name: 'Lettuce', type: 'Vegetable'),
        Ingredient(id: tomatoId, name: 'Tomato', type: 'Vegetable'),
      ],
      information: 'A protein-packed grilled chicken salad with fresh vegetables.',
      guide: [
        RecipeStep(description: 'Season chicken with salt and pepper.'),
        RecipeStep(description: 'Grill chicken until cooked through.', timer: 15),
        RecipeStep(description: 'Chop vegetables and mix in a bowl.'),
        RecipeStep(description: 'Top with grilled chicken slices and serve.', timer: 5),
      ],
    ));
    print('Grilled Chicken Salad Recipe added with ID: $grilledChickenSaladId');

    // Add the third recipe: Tomato Cheese Rice
    final tomatoCheeseRiceId = await recipeService.addRecipe(Recipe(
      id: '', // ID will be generated by Firebase
      name: 'Tomato Cheese Rice',
      image: 'assets/images/icons/tomato_rice.png',
      salt: '1.5g',
      fat: '8g',
      energy: '200kcal',
      protein: '10g',
      ingredients: [
        Ingredient(id: riceId, name: 'Rice', type: 'Grain'),
        Ingredient(id: tomatoId, name: 'Tomato', type: 'Vegetable'),
        Ingredient(id: cheeseId, name: 'Cheese', type: 'Dairy'),
      ],
      information: 'A delicious tomato and cheese rice dish, easy to make.',
      guide: [
        RecipeStep(description: 'Cook rice until tender.', timer: 20),
        RecipeStep(description: 'Sauté tomatoes in a pan.', timer: 10),
        RecipeStep(description: 'Mix rice and tomatoes, then top with cheese.'),
        RecipeStep(description: 'Bake until cheese is melted.', timer: 10),
      ],
    ));
    print('Tomato Cheese Rice Recipe added with ID: $tomatoCheeseRiceId');
  }
}